<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-27 08:36
=======
# Generated by Django 3.2.4 on 2021-07-27 06:41
>>>>>>> 66db7a8e3493f8b0dd75eea2a5f01d51657ea25d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='HelloWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
=======
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=25)),
>>>>>>> 66db7a8e3493f8b0dd75eea2a5f01d51657ea25d
            ],
        ),
    ]
