# Generated by Django 3.2.4 on 2021-07-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_rename_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
