# Generated by Django 3.2.5 on 2021-07-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='guide/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
