# Generated by Django 3.2.5 on 2021-07-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QNA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qna',
            new_name='Question',
        ),
    ]
