# Generated by Django 3.2.5 on 2021-07-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QNA', '0002_rename_qna_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='QNA/')),
            ],
        ),
    ]
