# Generated by Django 3.2.5 on 2021-07-26 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QNA', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QNA.question'),
        ),
    ]
