# Generated by Django 3.2.5 on 2021-07-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QNA', '0004_alter_answer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='question',
        ),
    ]
